# Generated by Django 2.2.14 on 2020-10-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201021_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='large',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='small',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemSize',
        ),
    ]
